package dpHelper.generators.codeElements;

import com.sun.source.tree.MethodTree;

import java.util.Map;


public class EConstructor extends AbstractEMethod {

   public EConstructor(String[] modifiers, String type, Map<String, String> param,
                       String[] body, ESourceCode enclosing) {
      super(modifiers, "", type, param, body, enclosing);
   }

   public EConstructor(MethodTree methodTree, ESourceCode enclosing) {
      super(methodTree, enclosing.getName(), enclosing);
      name = "";
   }

   @Override
   public String getKind() {
      return "CONSTRUCTOR";
   }

   public boolean isAutoGeneratedConstructor() {
      if (parameters.size() == 0 && getBody().size() == 1) {
         if (getBody().get(0).contains("super();")) ;
         return true;
      }
      return false;
   }


}
